name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        
      - name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.2
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

if-no-files-found:
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    
- name: Upload to Release Action
  # You may pin to the exact commit or the version.
  # uses: Shopify/upload-to-release@9942a4c936dab172f7101dcc7dc20528ea949102
  uses: Shopify/upload-to-release@v1.0.1
  with:
    # Artifact name
    name: staticsitegenerator
    # Path to the file to upload
    path: main
    # Content type for the file
    content-type: # optional, default is application/octet-stream
    
    repo-token: secrets.GITHUB_TOKEN
        
      
